enum Ejercicio {
    'PESO_M' = 1,
    'PESO_R',
    'GEMELO',
    'HT',
    'CURL',
    'MARTILLO',
    'ANT_MANC',
    'ANT_BARRA',
    'MAN_NEUTRO',
    'BAR_INV',
    'PRESS_BNC',
    'PRESS_MANC',
    'HOMBRO',
    'HOMBRO_F',
    'CRUCE',
    'BANCA_INCL',
    'HOMBRO_T',
    'REMO_MANC',
    'JALON_P',
    'TRI_CUERDA',
    'TRI_INV',
    'JALON_SENT',
    'PRESS_FR',
    'JALON_BARRA',
    'SENTADILLA',
    'BULGARA',
    'EXT_QUAD'
}
export default Ejercicio;